# Generated by Django 5.2.14 on 2026-08-29 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_user_google_sub'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSave',
            fields=[
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='vandao_save', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('data', models.JSONField()),
                ('revision', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vandao_saves',
            },
        ),
    ]
