# Generated by Django 5.2.14 on 2026-05-09 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('app', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=100)),
                ('data', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pk', models.CompositePrimaryKey('app', 'section', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'site_content',
                'ordering': ['app', 'section'],
            },
        ),
    ]
