# Generated by Django 5.2.14 on 2026-06-06 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.core.ids


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.CharField(default=apps.core.ids.new_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('icon', models.CharField(blank=True, default='', max_length=40)),
                ('color', models.CharField(blank=True, default='', max_length=20)),
                ('type', models.CharField(choices=[('binary', 'Binary'), ('count', 'Count')], default='binary', max_length=10)),
                ('target_count', models.PositiveIntegerField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, default='', max_length=24)),
                ('frequency', models.CharField(choices=[('daily', 'Every day'), ('weekly_days', 'Specific weekdays'), ('weekly_count', 'Times per week')], default='daily', max_length=16)),
                ('weekdays', models.JSONField(blank=True, default=list)),
                ('weekly_target', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, default='', max_length=40)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('reminder_enabled', models.BooleanField(default=False)),
                ('reminder_time', models.TimeField(blank=True, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('archived', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(db_column='user_id', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='habits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'habits',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='HabitLog',
            fields=[
                ('id', models.CharField(default=apps.core.ids.new_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('count', models.PositiveIntegerField(default=1)),
                ('completed', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('habit', models.ForeignKey(db_column='habit_id', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='habits.habit')),
                ('user', models.ForeignKey(db_column='user_id', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='habit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'habit_logs',
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='habit',
            index=models.Index(fields=['user', 'archived'], name='idx_habits_user_archived'),
        ),
        migrations.AddIndex(
            model_name='habitlog',
            index=models.Index(fields=['user', 'date'], name='idx_habit_logs_user_date'),
        ),
        migrations.AddConstraint(
            model_name='habitlog',
            constraint=models.UniqueConstraint(fields=('habit', 'date'), name='uq_habit_logs_habit_date'),
        ),
    ]
