# Generated by Django 5.2.14 on 2026-05-09 13:47

import apps.core.ids
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vibe',
            fields=[
                ('id', models.CharField(default=apps.core.ids.new_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('mood_emoji', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='vibes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vibes',
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='uq_vibes_user_date')],
            },
        ),
    ]
