# Generated by Django 5.2.14 on 2026-05-19 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vibe',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
