# Generated by Django 5.2.14 on 2026-05-19 16:49

import apps.core.ids
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_vibe_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StreakFreeze',
            fields=[
                ('id', models.CharField(default=apps.core.ids.new_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('applied_date', models.DateField()),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='streak_freezes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'streak_freezes',
                'ordering': ['-applied_date'],
                'constraints': [models.UniqueConstraint(fields=('user', 'applied_date'), name='uq_freeze_user_date')],
            },
        ),
    ]
