# Generated by Django 5.2.14 on 2026-06-06 17:17

from django.db import migrations, models

import apps.core.ids


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CafeReview',
            fields=[
                ('id', models.CharField(default=apps.core.ids.new_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('excerpt', models.CharField(blank=True, default='', max_length=300)),
                ('address', models.CharField(blank=True, default='', max_length=300)),
                ('district', models.CharField(blank=True, default='', max_length=80)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('price_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('price_note', models.CharField(blank=True, default='', max_length=120)),
                ('opening_hours', models.CharField(blank=True, default='', max_length=200)),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('rating_overall', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('rating_drink', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('rating_space', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('rating_price', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('rating_service', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('cover_image_url', models.URLField(blank=True, default='', max_length=500)),
                ('gallery', models.JSONField(blank=True, default=list)),
                ('content_md', models.TextField(blank=True, default='')),
                ('content_html', models.TextField(blank=True, default='')),
                ('is_published', models.BooleanField(default=False)),
                ('visited_at', models.DateField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cafe_reviews',
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['is_published', '-published_at'], name='idx_cafe_pub')],
            },
        ),
    ]
