# Generated by Django 5.2.14 on 2026-06-10 16:17

import django.db.models.deletion
from django.db import migrations, models

import apps.core.ids


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CafeAgentRun',
            fields=[
                ('id', models.CharField(default=apps.core.ids.new_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('slot', models.CharField(choices=[('daily', 'daily'), ('manual', 'manual')], default='manual', max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('started', 'started'), ('succeeded', 'succeeded'), ('skipped', 'skipped'), ('failed', 'failed')], default='started', max_length=16)),
                ('cafe_name', models.CharField(blank=True, default='', max_length=200)),
                ('error_message', models.TextField(blank=True, default='')),
                ('prompt', models.TextField(blank=True, default='')),
                ('agy_response_raw', models.TextField(blank=True, default='')),
                ('agy_response_parsed', models.JSONField(blank=True, null=True)),
                ('validation_error', models.TextField(blank=True, default='')),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('agy_duration_ms', models.IntegerField(blank=True, null=True)),
                ('review', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_runs', to='cafe.cafereview')),
            ],
            options={
                'db_table': 'cafe_agent_runs',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['status', 'started_at'], name='ix_car_status_started')],
            },
        ),
    ]
