# Generated by Django 5.2.14 on 2026-08-23 14:26

from django.db import migrations, models

import apps.core.ids


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_cafeagentrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='CafeImage',
            fields=[
                ('id', models.CharField(default=apps.core.ids.new_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('source_url', models.URLField(max_length=500, unique=True)),
                ('source_path', models.CharField(blank=True, default='', max_length=300)),
                ('riso_url', models.URLField(blank=True, default='', max_length=500)),
                ('riso_2x_url', models.URLField(blank=True, default='', max_length=500)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('palette_key', models.CharField(blank=True, db_index=True, default='', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cafe_images',
                'ordering': ['-created_at'],
            },
        ),
    ]
