# Generated by Django 5.2.14 on 2026-05-24 12:36

import apps.core.ids
import apps.quotes.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Baogia',
            fields=[
                ('id', models.CharField(default=apps.core.ids.new_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('share_token', models.CharField(default=apps.quotes.models._new_share_token, max_length=64, unique=True)),
                ('client_name', models.CharField(max_length=200)),
                ('client_company', models.CharField(blank=True, default='', max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True, default='')),
                ('currency', models.CharField(default='VND', max_length=8)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('issued_at', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(db_column='user_id', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='baogias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'baogias',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BaogiaLineItem',
            fields=[
                ('id', models.CharField(default=apps.core.ids.new_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=500)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('sort_order', models.IntegerField(default=0)),
                ('baogia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotes.baogia')),
            ],
            options={
                'db_table': 'baogia_line_items',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.CharField(default=apps.core.ids.new_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('author', models.CharField(blank=True, default='', max_length=200)),
                ('source', models.CharField(blank=True, default='', max_length=500)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('language', models.CharField(default='vi', max_length=8)),
                ('is_public', models.BooleanField(default=False)),
                ('is_curated', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, db_column='user_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='quotes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quotes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteFavorite',
            fields=[
                ('id', models.CharField(default=apps.core.ids.new_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quote', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='favorites', to='quotes.quote')),
                ('user', models.ForeignKey(db_column='user_id', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='quote_favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quote_favorites',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['is_curated', 'language'], name='ix_quotes_curated_lang'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['user', 'is_public'], name='ix_quotes_user_public'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['is_featured'], name='ix_quotes_featured'),
        ),
        migrations.AddConstraint(
            model_name='quotefavorite',
            constraint=models.UniqueConstraint(fields=('user', 'quote'), name='uq_quote_fav_user_quote'),
        ),
    ]
