# Generated by Django 5.2.14 on 2026-05-24 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baogialineitem',
            name='baogia',
        ),
        migrations.DeleteModel(
            name='Baogia',
        ),
        migrations.DeleteModel(
            name='BaogiaLineItem',
        ),
    ]
