# Generated by Django 5.2.14 on 2026-05-09 13:47

import apps.core.ids
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('name', models.CharField(db_column='key', max_length=80, primary_key=True, serialize=False)),
                ('value', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'app_settings',
            },
        ),
        migrations.CreateModel(
            name='LLMUsage',
            fields=[
                ('user_id', models.CharField(max_length=36)),
                ('date', models.DateField()),
                ('count', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pk', models.CompositePrimaryKey('user_id', 'date', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'llm_usage',
            },
        ),
        migrations.CreateModel(
            name='LLMJob',
            fields=[
                ('id', models.CharField(default=apps.core.ids.new_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=36)),
                ('username', models.CharField(default='', max_length=64)),
                ('mode', models.CharField(choices=[('random', 'Random'), ('polish', 'Polish'), ('remix', 'Remix')], max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='pending', max_length=16)),
                ('request_body', models.JSONField(blank=True, null=True)),
                ('result_scene', models.JSONField(blank=True, null=True)),
                ('error_message', models.CharField(blank=True, max_length=500, null=True)),
                ('attempt', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'llm_jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='idx_llm_jobs_status_created'), models.Index(fields=['user_id', 'created_at'], name='idx_llm_jobs_user_created')],
            },
        ),
        migrations.CreateModel(
            name='LLMRequestLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=36)),
                ('username', models.CharField(default='', max_length=64)),
                ('mode', models.CharField(max_length=16)),
                ('model', models.CharField(max_length=64)),
                ('attempt', models.PositiveSmallIntegerField(default=1)),
                ('temperature', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('request_payload', models.JSONField(blank=True, null=True)),
                ('response_raw', models.TextField(blank=True, null=True)),
                ('parsed_direction', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(max_length=24)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('latency_ms', models.IntegerField(default=0)),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'llm_request_logs',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['created_at'], name='idx_llm_logs_created'), models.Index(fields=['user_id', 'created_at'], name='idx_llm_logs_user')],
            },
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.CharField(default=apps.core.ids.new_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('favorite', 'Favorite'), ('upload', 'Upload'), ('snapshot', 'Snapshot')], default='snapshot', max_length=24)),
                ('source_id', models.CharField(blank=True, max_length=80, null=True)),
                ('title', models.CharField(max_length=80)),
                ('prompt', models.CharField(max_length=180)),
                ('style', models.CharField(max_length=40)),
                ('palette', models.CharField(max_length=60)),
                ('seed', models.BigIntegerField()),
                ('settings', models.JSONField(db_column='settings_json')),
                ('scene', models.JSONField(db_column='scene_json')),
                ('thumbnail_data_url', models.TextField()),
                ('asset_data_url', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(db_column='user_id', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='artworks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'artworks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='idx_artworks_user_created')],
            },
        ),
    ]
